In [24]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

In [25]:
df=pd.read_csv("C:/Users/Balaji/Desktop/SEM 6/ML&C Lab/Datasets/diabetes.csv")

In [26]:
df.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [27]:
x=df.iloc[:,0:8]
y=df.Outcome
print('x Shape: ',x.shape)
print('y Shape: ',y.shape)

x Shape:  (768, 8)
y Shape:  (768,)


In [28]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [29]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [30]:
scaler = StandardScaler()
x_std = scaler.fit_transform(x)

In [31]:
x_train , x_test , y_train , y_test = train_test_split(x_std ,y ,test_size=0.3 ,random_state=0)

In [32]:
print('x_train Shape: ',x_train.shape)
print('y_train Shape: ',y_train.shape)
print('x_train Shape: ',x_test.shape)
print('x_test Shape: ',x_test.shape)

x_train Shape:  (537, 8)
y_train Shape:  (537,)
x_train Shape:  (231, 8)
x_test Shape:  (231, 8)


In [33]:
mlp = MLPClassifier(hidden_layer_sizes=(55), activation='relu', max_iter=(200), verbose=True)
mlp

MLPClassifier(hidden_layer_sizes=55, verbose=True)

In [34]:
mlp.fit(x_train,y_train)

Iteration 1, loss = 0.62643139
Iteration 2, loss = 0.61387807
Iteration 3, loss = 0.60293128
Iteration 4, loss = 0.59235779
Iteration 5, loss = 0.58238102
Iteration 6, loss = 0.57370067
Iteration 7, loss = 0.56524193
Iteration 8, loss = 0.55781968
Iteration 9, loss = 0.55040560
Iteration 10, loss = 0.54385076
Iteration 11, loss = 0.53747553
Iteration 12, loss = 0.53175993
Iteration 13, loss = 0.52673511
Iteration 14, loss = 0.52139722
Iteration 15, loss = 0.51686240
Iteration 16, loss = 0.51217842
Iteration 17, loss = 0.50822389
Iteration 18, loss = 0.50416206
Iteration 19, loss = 0.50067076
Iteration 20, loss = 0.49729427
Iteration 21, loss = 0.49409095
Iteration 22, loss = 0.49099657
Iteration 23, loss = 0.48820829
Iteration 24, loss = 0.48556039
Iteration 25, loss = 0.48302595
Iteration 26, loss = 0.48089890
Iteration 27, loss = 0.47869565
Iteration 28, loss = 0.47656104
Iteration 29, loss = 0.47456268
Iteration 30, loss = 0.47283638
Iteration 31, loss = 0.47121352
Iteration 32, los

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=55, verbose=True)

In [35]:
print(mlp.score(x_train,y_train)*100)

82.12290502793296


In [36]:
mlp.fit(x_train,y_train)

Iteration 1, loss = 0.75777613
Iteration 2, loss = 0.73702230
Iteration 3, loss = 0.71671061
Iteration 4, loss = 0.69798250
Iteration 5, loss = 0.68066419
Iteration 6, loss = 0.66500302
Iteration 7, loss = 0.65038441
Iteration 8, loss = 0.63633973
Iteration 9, loss = 0.62306414
Iteration 10, loss = 0.61160604
Iteration 11, loss = 0.60098401
Iteration 12, loss = 0.59076032
Iteration 13, loss = 0.58137323
Iteration 14, loss = 0.57263048
Iteration 15, loss = 0.56445806
Iteration 16, loss = 0.55689301
Iteration 17, loss = 0.54979997
Iteration 18, loss = 0.54329924
Iteration 19, loss = 0.53745566
Iteration 20, loss = 0.53169161
Iteration 21, loss = 0.52651339
Iteration 22, loss = 0.52189121
Iteration 23, loss = 0.51722064
Iteration 24, loss = 0.51316520
Iteration 25, loss = 0.50926706
Iteration 26, loss = 0.50565102
Iteration 27, loss = 0.50207182
Iteration 28, loss = 0.49918538
Iteration 29, loss = 0.49636390
Iteration 30, loss = 0.49337365
Iteration 31, loss = 0.49087595
Iteration 32, los

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=55, verbose=True)

In [37]:
print(mlp.score(x_test,y_test)*100)

76.62337662337663


In [38]:
x_pred = mlp.predict(x_train)
x_pred

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,

In [39]:
y_pred = mlp.predict(x_test)
print(y_pred)

[1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0
 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 0 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0
 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 1 0
 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 1 1 1 0 0 0 0 0]


In [40]:
y_test.ravel()

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [41]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[139  18]
 [ 36  38]]


In [42]:
cr = classification_report(y_test ,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.79      0.89      0.84       157
           1       0.68      0.51      0.58        74

    accuracy                           0.77       231
   macro avg       0.74      0.70      0.71       231
weighted avg       0.76      0.77      0.76       231



In [43]:
print(x_test)

[[-0.84488505  2.44447821  0.35643175 ...  1.38436175  2.784923
  -0.95646168]
 [-0.54791859 -0.43485916  0.25303625 ...  0.20401277 -0.20499449
  -0.87137393]
 [ 0.04601433 -1.40507067 -0.36733675 ...  0.25478047 -0.24425603
  -0.70119842]
 ...
 [-0.84488505 -0.81042491 -0.47073225 ... -1.02710391 -0.63989158
  -0.95646168]
 [-0.84488505 -0.46615631  0.35643175 ...  0.69899783 -0.83015905
  -0.61611067]
 [ 1.82781311  0.03459802  0.45982725 ... -0.5575027   0.12117833
   1.00055664]]


In [44]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [45]:
sample = np.array([5,121,72,23,112,26.2,0.245,30])
print('Shape of sample: ',sample.shape)
print('Shape of x_test: ',x_test.shape)

sample = np.expand_dims(sample,0)
print('Shape of Exapand model: ',sample.shape)
mlp.predict(sample)

Shape of sample:  (8,)
Shape of x_test:  (231, 8)
Shape of Exapand model:  (1, 8)


array([1], dtype=int64)