In [19]:
import numpy as np
import pandas as pd

from sklearn import preprocessing , datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler, Normalizer , LabelEncoder
from sklearn.neural_network import MLPClassifier, MLPRegressor

In [2]:
x=np.random.random((10,5))  #dataset creation
print(x)

[[0.90070427 0.08998196 0.68231117 0.76165762 0.16280593]
 [0.30485977 0.02190799 0.04360326 0.36744491 0.70558126]
 [0.29224109 0.76608439 0.14433724 0.21460072 0.26506906]
 [0.12168862 0.18062911 0.58739106 0.0298715  0.38275593]
 [0.4962708  0.61251046 0.3203793  0.2928387  0.87238786]
 [0.41983203 0.63599988 0.29474268 0.75972678 0.21647524]
 [0.22868663 0.92599508 0.3290376  0.09118247 0.26790834]
 [0.28018623 0.91970223 0.92744708 0.71224487 0.670703  ]
 [0.90950293 0.56675221 0.6892355  0.08191425 0.35265036]
 [0.45951156 0.99095735 0.53919957 0.96198918 0.96857525]]


In [3]:
y=np.array(['M','F','N','F','M','N','F','N','M','N'])
y

array(['M', 'F', 'N', 'F', 'M', 'N', 'F', 'N', 'M', 'N'], dtype='<U1')

In [4]:
print(x.shape)
print(y.shape)

(10, 5)
(10,)


In [5]:
x_train, x_test , y_train , y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [6]:
scaler = StandardScaler()       #preprocessing

In [9]:
a=np.array([1,2,3,4,5,30,50])                     #1)Standardization 

In [10]:
print("Mean:",a.mean())
print("SD: ",a.std())

Mean: 13.571428571428571
SD:  17.589421681853015


In [11]:
#a_std=scaler.fit_transform(a.reshape(-1,1))
#print("Mean:",a.mean())
#print("SD: ",a.std())

xtrain_std=scaler.fit_transform(x_train)
xtest_std=scaler.transform(x_test)


In [12]:
print(xtrain_std.mean(), xtest_std.std())

-1.586032892321652e-17 0.9686114724629642


In [13]:
from sklearn.preprocessing import LabelEncoder
enco=LabelEncoder()

In [16]:
y_enc=enco.fit_transform(y_train)
yt_enc = enco.fit_transform(y_test)
yt_enc

array([1, 0, 0], dtype=int64)

In [17]:
#unsupervised

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA


In [20]:
#MOdel fitting

mlp = MLPClassifier()
print(xtrain_std.shape , y_enc.shape)

mlp.fit(xtrain_std,y_enc)

(7, 5) (7,)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [22]:
print(mlp.score(xtrain_std, y_enc)*100)
print(mlp.score(xtest_std,yt_enc )*100)

100.0
33.33333333333333


In [23]:
y_pred = mlp.predict(x_test)
print(y_pred)


[2 2 2]


In [24]:
from sklearn.metrics import classification_report

In [28]:
cm = confusion_matrix(yt_enc, y_pred)
print(cm)

[[0 0 2]
 [0 0 1]
 [0 0 0]]


In [29]:
cr = classification_report(yt_enc, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       2.0
           1       0.00      0.00      0.00       1.0
           2       0.00      0.00      0.00       0.0

    accuracy                           0.00       3.0
   macro avg       0.00      0.00      0.00       3.0
weighted avg       0.00      0.00      0.00       3.0



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_cla